receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256

  batch:
    timeout: 5s
    send_batch_size: 512

  filter/biz_metrics:
    error_mode: ignore
    metrics:
      metric:
        - 'not(IsMatch(name, "^biz\\..+"))'

  filter/app_metrics:
    error_mode: ignore
    metrics:
      metric:
        - 'IsMatch(name, "^biz\\..+")'

exporters:
  otlp/newrelic:
    endpoint: ${env:NEW_RELIC_OTLP_ENDPOINT}
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}

  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true
    metric_expiration: 3m

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/newrelic]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/newrelic]

    metrics/biz:
      receivers: [otlp]
      processors: [memory_limiter, filter/biz_metrics, batch]
      exporters: [prometheus]

    metrics/app:
      receivers: [otlp]
      processors: [memory_limiter, filter/app_metrics, batch]
      exporters: [otlp/newrelic]

  telemetry:
    logs:
      level: warn
