

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: normal #basic, normal, detailed
  
  otlp/aspire:
    endpoint: "aspiredashboard:18889" #GRPC
    tls:
      insecure: true

  otlphttp/openobserve:
    endpoint: "http://openobserve:5080/api/default"
    headers:
      Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpIQ2VJWWxyenFOMjJyU2R6

  prometheus:
    endpoint: "0.0.0.0:9464" # Prometheus pulls metrics from here
    send_timestamps: false
    metric_expiration: 180m
    enable_open_metrics: false

processors:
  cumulative_to_delta:

  resource: #transform https://opentelemetry.io/docs/collector/transforming-telemetry/
    attributes:
      - key: parent_id
        from_attribute: parentid
        action: insert
      - key: span.kind
        from_attribute: Span.kind
        action: insert
      - key: span_id
        from_attribute: SpanId
        action: insert

      - key: trace_id
        from_attribute: TraceId
        action: insert

      # - action: delete
      #   key: "telemetry.sdk.name"
      # - action: insert
      #   key: "serviceid"
      #   from_attribute: "service.name"
      # - action: delete
      #   key: service.name

  batch:
    timeout: 10s
    send_batch_size: 10000
    send_batch_max_size: 11000
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800

service:
  #extensions: [health_check]
  telemetry:
    logs:
      level: "info"  #debug, info,warn,error   

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/aspire, otlphttp/openobserve] #, logging, otlp/jaeger, ,otlp/newrelic, elasticsearch/traces
    logs:
      receivers: [otlp]
      processors: [ resource, batch] # ,resource
      exporters: [otlp/aspire, otlphttp/openobserve] # loki, otlp/elastic, , otlp/newrelic, elasticsearch/logs
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, cumulative_to_delta, batch, resource] #metricstransform/rename,
      exporters: [otlp/aspire, prometheus, otlphttp/openobserve] # , otlp/newrelic, prometheus,