# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "0.0.0.0"

# The URLs of the Elasticsearch instances to use for all your queries.
elasticsearch.hosts: ["http://elasticsearch:9200"]
#elasticsearch.username: kibana_system
#elasticsearch.password: changeme
#elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYTo4dXdQMHZkWVFrR2NkMnNkNm9DenF3"
