apm-server:
  host: "0.0.0.0:8200"
  auth:
    secret_token: ""
    anonymous:
      enabled: true
      allow_service: []

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: http

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
logging.to_files: false
