---

services:

  aspiredashboard:
     hostname: aspiredashboard
     image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
     ports:
       - "18888:18888" #UI
       - "18889:18889" #GRPC
     restart: always
     environment:
       - DOTNET_DASHBOARD_OTLP_GRPCENDPOINT=0.0.0.0:18889    
