---

services:

  aspiredashboard:
      hostname: aspiredashboard
      container_name: aspiredashboard
      depends_on:
       - otelcol
      image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
      ports:
        - "18888:18888" #UI
        - "18889:18889" #GRPC
      restart: always
      environment:
        DOTNET_DASHBOARD_OTLP_GRPCENDPOINT: 0.0.0.0:18889    
        DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true

  otelcol:
    hostname: otelcol
    container_name: otelcol
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/otel-collector-config.yaml"]
    env_file:
      - .env
    ports:  
      - 8888:8888      # Prometheus metrics exposed by the collector    
      - 9464:9464      # Prometheus Metrics    
      - 4317:4317      # OTLP gRPC receiver
      - 4318:4318      # OTLP HTTP receiver
      - 13133:13133    # health
      #- 8006:8006     # fluentdforward
      #- 8006:8006/udp # fluentforward
    volumes:
      - ./config/apm/${OTELC_CONFIG}/otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=otel-collector
      - ELASTIC_API_KEY=elasticsearch-apikey 
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=eu01xxe66fa290a6436adb2d21e0883dFFFFNRAL
    depends_on:
      - prometheus

  grafana:
      hostname: grafana
      container_name: grafana  
      image: grafana/grafana:12.0.2
      volumes:
          - ./config/stack/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
          - ./docker_data/grafana_data:/var/lib/grafana
      environment:
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
          - GF_AUTH_DISABLE_LOGIN_FORM=true
          - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
         #- GF_INSTALL_PLUGINS=frser-sqlite-datasource,grafana-newrelic-datasource,grafana-opensearch-datasource"
         #- GF_PLUGINS_PREINSTALL =frser-sqlite-datasource,grafana-newrelic-datasource 12.4.0 https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#installing-grafana-plugins
      ports:
          - "3000:3000"
      depends_on:
          - prometheus      

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    hostname: mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=all
    ports:
      # Mimir API and Prometheus-compatible endpoints
      - "9009:9009"
    volumes:
      - ./config/stack/mimir.yaml:/etc/mimir.yaml
      - ./docker_data/mimir:/data
    # restart: unless-stopped

  prometheus:
    hostname: prometheus
    container_name: prometheus
    image: prom/prometheus:v3.4.1
    command:
        - --config.file=/etc/prometheus.yaml
        - --web.enable-remote-write-receiver
        - --enable-feature=exemplar-storage
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=15d
    volumes:
        - ./config/stack/prometheus.yaml:/etc/prometheus.yaml
        - ./docker_data/prometheus:/prometheus:rw
    ports:
        - "9090:9090"
